[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
startCommand = "NONE"

[env]
PYTHON_VERSION = "3.11"
NODE_VERSION = "16.20.0"
NPM_VERSION = "8.19.4"
GEMINI_MODEL = "gemini-2.0-flash"
WEB3_PROVIDER_URL = "https://coston2-api.flare.network/ext/C/rpc"
WEB3_EXPLORER_URL = "https://coston2-explorer.flare.network/"
SIMULATE_ATTESTATION = "true"
CORS_ORIGINS = '["*"]'
API_VERSION = "v1"
CHAIN_ID = "114"
PYTHONPATH = "/app/src" 